name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [7.4]
        node-version: [14.7]
    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "db_blog"
          MYSQL_USER: "test"
          MYSQL_PASSWORD: "test"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/php-setup@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-
      - name: Run build
        run: make build
